/*********************************************************************
*  <이든 수식편집>
*  위지윅 방식의 웹기반 수식편집기 입니다.
*  솔루션 구성은 클라이언트 모듈과 서버 모듈(java)로 구성되어 있습니다.
*  위지윅 방식으로 쉽게 수식입력이 가능하며 latex 문법으로도 수식입력이 가능합니다.
*  작성한 수식은 latex 및 mathml 또는 이미지로 변환이 가능하여 수식 답안 작성 및 게시판등에
*  이용이 가능합니다.    
*  무단 사용 및 배포를 금지합니다.  
*  솔루션 구입 연락처 : edenit@edenitsolution.com (02-2299-8250)
*  
*  EdenMath Editor
*  VERSION : 1.0.1
*  DOCS & DEMO : http://edenitsolution.com (http://edenit.co.kr)
*  CONTACT : edenit@edenitsolution.com
*  TEL : +82-02-2299-8250
*  
*  EdenMath Editor is web based wysiwyg math editor
*  support latex, mathml and image rendering
*  
*  Copyright (c) 2015-2016 by EDENIT Co.,Ltd  All Rights Reserved
*********************************************************************/

(function(){function B(){}function b(a){var b=T.call(arguments,1);return function(){return a.apply(this,b)}}function w(a,b){if(!b)throw Error("prayer failed: "+a);}function E(a){w("a direction was passed",-1===a||1===a)}function aa(a,b,f,c){function n(){g=U;var a=m.selection?"$"+m.selection.latex()+"$":"";h.select(a)}var G=a.contents().detach();f||a.addClass("mathquill-rendered-math");b.jQ=a.attr("mathquill-block-id",b.id);b.revert=function(){a.empty().unbind(".mathquill").removeClass("mathquill-rendered-math mathquill-editable mathquill-textbox").append(G)};
var m=b.cursor=fa(b);b.renderLatex(G.text());var u=b.textarea=r('<span class="textarea"><textarea></textarea></span>'),d=u.children(),g;b.selectionChanged=function(){g===U&&(g=setTimeout(n));ba(a[0])};a.bind("selectstart.mathquill",function(a){a.target!==d[0]&&a.preventDefault();a.stopPropagation()});var y,k=m.blink;a.bind("mousedown.mathquill",function(f){function n(a){m.seek(r(a.target),a.pageX,a.pageY);m[-1]===y[-1]&&m.parent===y.parent||"editable-math"!=y.parent.jQ[0].id||m.selectFrom(y);return!1}
function b(a){delete a.target;return n(a)}function z(f){y=U;m.blink=k;m.selection||(c?m.show():u.detach());a.unbind("mousemove",n);r(f.target.ownerDocument).unbind("mousemove",b).unbind("mouseup",z)}setTimeout(function(){d.focus();d.focused=!0});m.blink=B;m.seek(r(f.target),f.pageX,f.pageY);y=V(m.parent,m[-1],m[1]);c||d.focused||a.prepend(u);a.mousemove(n);r(f.target.ownerDocument).mousemove(b).mouseup(z);return!1});if(c)h=ca(d,{container:a,key:function(a,f){m.parent.bubble("onKey",a,f)},text:function(a){m.parent.bubble("onText",
a)},cut:function(a){m.selection&&setTimeout(function(){m.prepareEdit();m.parent.bubble("redraw")});a.stopPropagation()},paste:function(a){a="$"===a.slice(0,1)&&"$"===a.slice(-1)?a.slice(1,-1):"\\text{"+a+"}";m.writeLatex(a).show()}}),a.prepend(u),a.addClass("mathquill-editable"),f&&a.addClass("mathquill-textbox"),d.focus(function(a){m.parent||m.insAtRightEnd(b);m.parent.jQ.addClass("hasCursor");m.selection?(m.selection.jQ.removeClass("blur"),setTimeout(b.selectionChanged)):m.show();a.stopPropagation()}).blur(function(a){m.hide().parent.blur();
m.selection&&m.selection.jQ.addClass("blur");a.stopPropagation()}),a.bind("focus.mathquill blur.mathquill",function(a){d.trigger(a)}).blur();else{var l=function(){u.detach();d.focused=!1},h=ca(d,{container:a});a.bind("cut paste",!1).bind("copy",n).prepend('<span class="selectable">$'+b.latex()+"$</span>");d.blur(function(){m.clearSelection();setTimeout(l)})}}function I(a,b,f){return g(P,{ctrlSeq:a,htmlTemplate:"<"+b+" "+f+">&0</"+b+">"})}var H=window.jQuery,U,M=Math.min,T=[].slice,g=function(a,b,
f){function c(a){return"function"===typeof a}function n(){}return function m(d,g){function t(){var a=new y;c(a.init)&&a.init.apply(a,arguments);return a}function y(){}g===f&&(g=d,d=Object);t.Bare=y;var k=n[a]=d[a],l=y[a]=t[a]=t.p=new n,h;l.constructor=t;t.mixin=function(f){y[a]=t[a]=m(t,f)[a];return t};return(t.open=function(a){h={};c(a)?h=a.call(t,l,k,t,d):"object"===typeof a&&(h=a);if("object"===typeof h)for(var f in h)b.call(h,f)&&(l[f]=h[f]);c(l.init)||(l.init=d);return t})(g)}}("prototype",{}.hasOwnProperty),
ca=function(){function a(f){var c=f.which||f.keyCode,e=b[c],d=[];f.ctrlKey&&d.push("Ctrl");f.originalEvent&&f.originalEvent.metaKey&&d.push("Meta");f.altKey&&d.push("Alt");f.shiftKey&&d.push("Shift");f=e||String.fromCharCode(c);if(!d.length&&!e)return f;d.push(f);return d.join("-")}var b={8:"Backspace",9:"Tab",10:"Enter",13:"Enter",16:"Shift",17:"Control",18:"Alt",20:"CapsLock",27:"Esc",32:"Spacebar",33:"PageUp",34:"PageDown",35:"End",36:"Home",37:"Left",38:"Up",39:"Right",40:"Down",45:"Insert",46:"Del",
144:"NumLock"};return function(f,c){function b(a){var f=h.val();h.val("");f&&a(f)}function d(){var a;a=h[0];a="selectionStart"in a?a.selectionStart!==a.selectionEnd:!1;a||b(t)}function z(){b(l)}var u=null,g=null;c||(c={});var t=c.text||B,y=c.key||B,l=c.paste||B,k=c.cut||B,h=H(f),r=H(c.container||h),p=B,q;r.bind("keydown keypress input keyup focusout paste",function(){p()});r.bind({keydown:function(f){u=f;g=null;y(a(u),u);p=d;clearTimeout(q);q=setTimeout(d)},keypress:function(f){u&&g&&y(a(u),u);g=
f},focusout:function(){u=g=null},cut:k,paste:function(a){h.focus();p=z;clearTimeout(q);q=setTimeout(z)}});return{select:function(a){p();p=B;clearTimeout(q);h.val(a);a&&h[0].select()}}}}(),q=g(function(a,b,f){function c(a,f){throw"Parse Error: "+f+" at "+(a?"'"+a+"'":"EOF");}a.init=function(a){this._=a};a.parse=function(a){return this.skip(d)._(a,function(a,f){return f},c)};a.or=function(a){w("or is passed a parser",a instanceof f);var c=this;return f(function(f,e,b){return c._(f,e,function(c){return a._(f,
e,b)})})};a.then=function(a){var c=this;return f(function(e,b,n){return c._(e,function(c,e){var d=a instanceof f?a:a(e);w("a parser is returned",d instanceof f);return d._(c,b,n)},n)})};a.many=function(){var a=this;return f(function(f,c,e){function b(a,c){f=a;d.push(c);return!0}function n(){return!1}for(var d=[];a._(f,b,n););return c(f,d)})};a.times=function(a,c){2>arguments.length&&(c=a);var e=this;return f(function(f,b,n){function d(a,c){g.push(c);f=a;return!0}function z(a,c){l=c;f=a;return!1}function G(a,
f){return!1}for(var g=[],h=!0,l,k=0;k<a;k+=1)if(h=e._(f,d,z),!h)return n(f,l);for(;k<c&&h;k+=1)h=e._(f,d,G);return b(f,g)})};a.result=function(a){return this.then(n(a))};a.atMost=function(a){return this.times(0,a)};a.atLeast=function(a){var f=this;return f.times(a).then(function(a){return f.many().map(function(f){return a.concat(f)})})};a.map=function(a){return this.then(function(f){return n(a(f))})};a.skip=function(a){return this.then(function(f){return a.result(f)})};this.string=function(a){var c=
a.length,e="expected '"+a+"'";return f(function(f,b,n){var d=f.slice(0,c);return d===a?b(f.slice(c),d):n(f,e)})};a=this.regex=function(a){w("regexp parser is anchored","^"===a.toString().charAt(1));var c="expected "+a;return f(function(f,e,b){var n=a.exec(f);return n?(b=n[0],e(f.slice(b.length),b)):b(f,c)})};var n=f.succeed=function(a){return f(function(f,c){return c(f,a)})};f.fail=function(a){return f(function(f,c,e){return e(f,a)})};f.letter=a(/^[a-z]/i);f.letters=a(/^[a-z]*/i);f.digit=a(/^[0-9]/);
f.digits=a(/^[0-9]*/);f.whitespace=a(/^\s+/);f.optWhitespace=a(/^\s*/);f.any=f(function(a,f,c){return a?f(a.slice(1),a.charAt(0)):c(a,"expected any character")});f.all=f(function(a,f,c){return f("",a)});var d=f.eof=f(function(a,f,c){return a?c(a,"expected EOF"):f(a,a)})}),r=g(H,function(a){a.insDirOf=function(a,f){return-1===a?this.insertBefore(f.first()):this.insertAfter(f.last())};a.insAtDirEnd=function(a,f){return-1===a?this.prependTo(f):this.appendTo(f)}}),V=g(function(a){a.parent=0;a[-1]=0;a[1]=
0;a.init=function(a,f,c){this.parent=a;this[-1]=f;this[1]=c}}),W=g(function(a){a[-1]=0;a[1]=0;a.parent=0;a.init=function(){this.ends={};this.ends[-1]=0;this.ends[1]=0};a.children=function(){return Q(this.ends[-1],this.ends[1])};a.eachChild=function(a){return this.children().each(a)};a.foldChildren=function(a,f){return this.children().fold(a,f)};a.adopt=function(a,f,c){Q(this,this).adopt(a,f,c);return this};a.disown=function(){Q(this,this).disown();return this}}),Q=g(function(a){function b(a,c,e){w("a parent is always present",
a);var d;d=c?c[1]===e&&c.parent===a:a.ends[-1]===e;w("leftward is properly set up",d);a=e?e[-1]===c&&e.parent===a:a.ends[1]===c;w("rightward is properly set up",a)}a.init=function(a,c){w("no half-empty fragments",!a===!c);this.ends={};a&&(w("left end node is passed to Fragment",a instanceof W),w("right end node is passed to Fragment",c instanceof W),w("leftEnd and rightEnd have the same parent",a.parent===c.parent),this.ends[-1]=a,this.ends[1]=c)};a.adopt=function(a,c,e){b(a,c,e);this.disowned=!1;
var d=this.ends[-1];if(!d)return this;var m=this.ends[1];c||(a.ends[-1]=d);e?e[-1]=m:a.ends[1]=m;this.ends[1][1]=e;this.each(function(e){e[-1]=c;e.parent=a;c&&(c[1]=e);c=e});return this};a.disown=function(){var a=this.ends[-1];if(!a||this.disowned)return this;this.disowned=!0;var c=this.ends[1],e=a.parent;b(e,a[-1],a);b(e,c,c[1]);a[-1]?a[-1][1]=c[1]:e.ends[-1]=c[1];c[1]?c[1][-1]=a[-1]:e.ends[1]=a[-1];return this};a.each=function(a){var c=this.ends[-1];if(!c)return this;for(;c!==this.ends[1][1]&&!1!==
a.call(this,c);c=c[1]);return this};a.fold=function(a,c){this.each(function(e){a=c.call(this,a,e)});return a}}),ga=function(){var a=0;return function(){return a+=1}}(),p=g(W,function(a,b){a.init=function(a){b.init.call(this);this.id=ga();p[this.id]=this};a.toString=function(){return"[MathElement "+this.id+"]"};a.bubble=function(a){for(var c=T.call(arguments,1),e=this;e&&!1!==(e[a]&&e[a].apply(e,c));e=e.parent);return this};a.postOrder=function(a){var c=T.call(arguments,1);if("string"===typeof a){var e=
a;a=function(a){e in a&&a[e].apply(a,c)}}(function m(c){c.eachChild(m);a(c)})(this)};a.jQ=r();a.jQadd=function(a){this.jQ=this.jQ.add(a)};this.jQize=function(a){a=r(a);a.find("*").andSelf().each(function(){var a=r(this),f=a.attr("mathquill-command-id"),e=a.attr("mathquill-block-id");f&&p[f].jQadd(a);e&&p[e].jQadd(a)});return a};a.finalizeInsert=function(){this.postOrder("finalizeTree");this.postOrder("blur");this.postOrder("respace");this[1].respace&&this[1].respace();this[-1].respace&&this[-1].respace();
this.postOrder("redraw");this.bubble("redraw")}}),h=g(p,function(a,b){a.init=function(a,c,e){b.init.call(this);this.ctrlSeq||(this.ctrlSeq=a);c&&(this.htmlTemplate=c);e&&(this.textTemplate=e)};a.replaces=function(a){a.disown();this.replacedFragment=a};a.isEmpty=function(){return this.foldChildren(!0,function(a,c){return a&&c.isEmpty()})};a.parser=function(){var a=this;return J.block.times(a.numBlocks()).map(function(c){a.blocks=c;for(var e=0;e<c.length;e+=1)c[e].adopt(a,a.ends[1],0);return a})};a.createLeftOf=
function(a){var c=this.replacedFragment;this.createBlocks();p.jQize(this.html());c&&(c.adopt(this.ends[-1],0,0),c.jQ.appendTo(this.ends[-1].jQ));a.jQ.before(this.jQ);a[-1]=this.adopt(a.parent,a[-1],a[1]);this.finalizeInsert(a);this.placeCursor(a)};a.createBlocks=function(){for(var a=this.numBlocks(),c=this.blocks=Array(a),e=0;e<a;e+=1)(c[e]=A()).adopt(this,this.ends[1],0)};a.respace=B;a.placeCursor=function(a){a.insAtRightEnd(this.foldChildren(this.ends[-1],function(a,f){return a.isEmpty()?a:f}))};
a.remove=function(){this.disown();this.jQ.remove();this.postOrder(function(a){delete p[a.id]});return this};a.numBlocks=function(){var a=this.htmlTemplate.match(/&\d+/g);return a?a.length:0};a.html=function(){var a=this.blocks,c=" mathquill-command-id="+this.id,e=this.htmlTemplate.match(/<[^<>]+>|[^<>]+/g);w("no unmatched angle brackets",e.join("")===this.htmlTemplate);for(var b=0,d=e[0];d;b+=1,d=e[b])if("/>"===d.slice(-2))e[b]=d.slice(0,-2)+c+"/>";else if("<"===d.charAt(0)){w("not an unmatched top-level close tag",
"/"!==d.charAt(1));e[b]=d.slice(0,-1)+c+">";var z=1;do b+=1,d=e[b],w("no missing close tags",d),"</"===d.slice(0,2)?--z:"<"===d.charAt(0)&&"/>"!==d.slice(-2)&&(z+=1);while(0<z)}return e.join("").replace(/>&(\d+)/g,function(c,e){return" mathquill-block-id="+a[e].id+">"+a[e].join("html")})};a.latex=function(){return this.foldChildren(this.ctrlSeq,function(a,c){return a+"{"+(c.latex()||" ")+"}"})};a.textTemplate=[""];a.text=function(){var a=this,c=0;return a.foldChildren(a.textTemplate[c],function(e,
b){c+=1;var d=b.text();return e&&"("===a.textTemplate[c]&&"("===d[0]&&")"===d.slice(-1)?e+d.slice(1,-1)+a.textTemplate[c]:e+b.text()+(a.textTemplate[c]||"")})}}),C=g(h,function(a,b){a.init=function(a,c,e){e||(e=a&&1<a.length?a.slice(1):a);b.init.call(this,a,c,[e])};a.parser=function(){return q.succeed(this)};a.numBlocks=function(){return 0};a.replaces=function(a){a.remove()};a.createBlocks=B;a.latex=function(){return this.ctrlSeq};a.text=function(){return this.textTemplate};a.placeCursor=B;a.isEmpty=
function(){return!0}}),A=g(p,function(e){e.join=function(a){return this.foldChildren("",function(f,c){return f+c[a]()})};e.latex=function(){return this.join("latex")};e.text=function(){return this.ends[-1]===this.ends[1]?this.ends[-1].text():"("+this.join("text")+")"};e.isEmpty=function(){return 0===this.ends[-1]&&0===this.ends[1]};e.write=function(e,f,c){var b;b=f.match(/^[a-eg-zA-Z]$/)?v(f):(b=x[f]||a[f])?b(f):d(f);c&&b.replaces(c);b.createLeftOf(e)};e.focus=function(){this.jQ.addClass("hasCursor");
this.jQ.removeClass("empty");return this};e.blur=function(){this.jQ.removeClass("hasCursor");this.isEmpty()&&this.jQ.addClass("empty");return this}}),R=g(Q,function(a,b){a.init=function(a,c){b.init.call(this,a,c||a);this.jQ=this.fold(r(),function(a,c){return c.jQ.add(a)})};a.latex=function(){return this.fold("",function(a,c){return a+c.latex()})};a.remove=function(){this.jQ.remove();this.each(function(a){a.postOrder(function(a){delete p[a.id]})});return this.disown()}}),N=g(A,function(a,b){a.latex=
function(){return b.latex.call(this).replace(/(\\[a-z]+) (?![a-z])/ig,"$1")};a.text=function(){return this.foldChildren("",function(a,c){return a+c.text()})};a.renderLatex=function(a){this.jQ.children().slice(1).remove();this.ends[-1]=this.ends[1]=0;delete this.cursor.selection;this.cursor.insAtRightEnd(this).writeLatex(a)};a.onKey=function(a,c){switch(a){case "Ctrl-Shift-Backspace":case "Ctrl-Backspace":for(;this.cursor[-1]||this.cursor.selection;)this.cursor.backspace();break;case "Shift-Backspace":case "Backspace":this.cursor.backspace();
break;case "Esc":case "Tab":case "Spacebar":var e=this.cursor.parent;if(e===this.cursor.root){"Spacebar"===a&&c.preventDefault();return}this.cursor.prepareMove();e[1]?this.cursor.insAtLeftEnd(e[1]):this.cursor.insRightOf(e.parent);break;case "Shift-Tab":case "Shift-Esc":case "Shift-Spacebar":e=this.cursor.parent;if(e===this.cursor.root){"Shift-Spacebar"===a&&c.preventDefault();return}this.cursor.prepareMove();e[-1]?this.cursor.insAtRightEnd(e[-1]):this.cursor.insLeftOf(e.parent);break;case "Enter":break;
case "End":this.cursor.prepareMove().insAtRightEnd(this.cursor.parent);break;case "Ctrl-End":this.cursor.prepareMove().insAtRightEnd(this);break;case "Shift-End":for(;this.cursor[1];)this.cursor.selectRight();break;case "Ctrl-Shift-End":for(;this.cursor[1]||this.cursor.parent!==this;)this.cursor.selectRight();break;case "Home":this.cursor.prepareMove().insAtLeftEnd(this.cursor.parent);break;case "Ctrl-Home":this.cursor.prepareMove().insAtLeftEnd(this);break;case "Shift-Home":for(;this.cursor[-1];)this.cursor.selectLeft();
break;case "Ctrl-Shift-Home":for(;this.cursor[-1]||this.cursor.parent!==this;)this.cursor.selectLeft();break;case "Left":this.cursor.moveLeft();break;case "Shift-Left":this.cursor.selectLeft();break;case "Ctrl-Left":break;case "Right":this.cursor.moveRight();break;case "Shift-Right":this.cursor.selectRight();break;case "Ctrl-Right":break;case "Up":this.cursor.moveUp();break;case "Down":this.cursor.moveDown();break;case "Shift-Up":if(this.cursor[-1])for(;this.cursor[-1];)this.cursor.selectLeft();else this.cursor.selectLeft();
case "Shift-Down":if(this.cursor[1])for(;this.cursor[1];)this.cursor.selectRight();else this.cursor.selectRight();case "Ctrl-Up":break;case "Ctrl-Down":break;case "Ctrl-Shift-Del":case "Ctrl-Del":for(;this.cursor[1]||this.cursor.selection;)this.cursor.deleteForward();break;case "Shift-Del":case "Del":this.cursor.deleteForward();break;case "Meta-A":case "Ctrl-A":if(this!==this.cursor.root)return;for(this.cursor.prepareMove().insAtRightEnd(this);this.cursor[-1];)this.cursor.selectLeft();break;default:return!1}c.preventDefault();
return!1};a.onText=function(a){this.cursor.write(a);return!1}}),X=g(h,function(a,b){a.init=function(a){b.init.call(this,"$");this.cursor=a};a.htmlTemplate='<span class="mathquill-rendered-math">&0</span>';a.createBlocks=function(){this.ends[-1]=this.ends[1]=N();this.blocks=[this.ends[-1]];this.ends[-1].parent=this;this.ends[-1].cursor=this.cursor;this.ends[-1].write=function(a,c,e){"$"!==c?A.prototype.write.call(this,a,c,e):this.isEmpty()?(a.insRightOf(this.parent).backspace().show(),d("\\$","$").createLeftOf(a)):
a[1]?a[-1]?A.prototype.write.call(this,a,c,e):a.insLeftOf(this.parent):a.insRightOf(this.parent)}};a.latex=function(){return"$"+this.ends[-1].latex()+"$"}}),ha=g(A,function(a){a.renderLatex=function(a){var f=this.cursor;this.jQ.children().slice(1).remove();this.ends[-1]=this.ends[1]=0;delete f.selection;f.show().insAtRightEnd(this);var c=q.regex,e=q.string,b=q.eof,m=q.all,u=e("$").then(J).skip(e("$").or(b)).map(function(a){var c=X(f);c.createBlocks();var e=c.ends[-1];a.children().adopt(e,0,0);return c}),
c=e("\\$").result("$").or(c(/^[^$]/)).map(d);if(a=u.or(c).many().skip(b).or(m.result(!1)).parse(a)){for(b=0;b<a.length;b+=1)a[b].adopt(this,this.ends[1],0);a=this.join("html");p.jQize(a).appendTo(this.jQ);this.finalizeInsert()}};a.onKey=function(a){"Spacebar"!==a&&"Shift-Spacebar"!==a&&N.prototype.onKey.apply(this,arguments)};a.onText=N.prototype.onText;a.write=function(a,e,c){c&&c.remove();if("$"===e)X(a).createLeftOf(a);else{var b;"<"===e?b="&lt;":">"===e&&(b="&gt;");d(e,b).createLeftOf(a)}}}),
x={},a={},F,ba=B,l=document.createElement("div").style,K={transform:1,WebkitTransform:1,MozTransform:1,OTransform:1,msTransform:1},Y,Z;for(Z in K)if(Z in l){Y=Z;break}Y?F=function(a,b,f){a.css(Y,"scale("+b+","+f+")")}:"filter"in l?(ba=function(a){a.className=a.className},F=function(a,b,f){function c(){a.css("marginRight",(d.width()-1)*(b-1)/b+"px")}b/=1+(f-1)/2;a.css("fontSize",f+"em");a.hasClass("matrixed-container")||a.addClass("matrixed-container").wrapInner('<span class="matrixed"></span>');var d=
a.children().css("filter","progid:DXImageTransform.Microsoft.Matrix(M11="+b+",SizingMethod='auto expand')");c();var G=setInterval(c);r(window).load(function(){clearTimeout(G);c()})}):F=function(a,b,f){a.css("fontSize",f+"em")};l=g(h,function(a,b){a.init=function(a,c,e){b.init.call(this,a,"<"+c+" "+e+">&0</"+c+">")}});a.mathrm=b(l,"\\mathrm","span",'class="roman font"');a.mathit=b(l,"\\mathit","i",'class="font"');a.mathbf=b(l,"\\mathbf","b",'class="font"');a.mathsf=b(l,"\\mathsf","span",'class="sans-serif font"');
a.mathtt=b(l,"\\mathtt","span",'class="monospace font"');a.underline=b(l,"\\underline","span",'class="non-leaf underline"');a.overline=a.bar=b(l,"\\overline","span",'class="non-leaf overline"');var D=g(h,function(a,b){a.init=function(a,c,e){b.init.call(this,a,"<"+c+' class="non-leaf">&0</'+c+">",[e])};a.finalizeTree=function(){function a(c){var e=this.parent,f=c;do{if(f[1])return c.insLeftOf(e),!1;f=f.parent.parent}while(f!==e);c.insRightOf(e);return!1}w("SupSub is only _ and ^","^"===this.ctrlSeq||
"_"===this.ctrlSeq);"_"===this.ctrlSeq?(this.down=this.ends[-1],this.ends[-1].up=a):(this.up=this.ends[-1],this.ends[-1].down=a)};a.latex=function(){var a=this.ends[-1].latex();return 1===a.length?this.ctrlSeq+a:this.ctrlSeq+"{"+(a||" ")+"}"};a.redraw=function(){this[-1]&&this[-1].respace();this[-1]instanceof D||(this.respace(),!this[1]||this[1]instanceof D||this[1].respace())};a.respace=function(){"\\int "===this[-1].ctrlSeq||this[-1]instanceof D&&this[-1].ctrlSeq!=this.ctrlSeq&&this[-1][-1]&&"\\int "===
this[-1][-1].ctrlSeq?this.limit||(this.limit=!0,this.jQ.addClass("limit")):"\\sum "===this[-1].ctrlSeq||this[-1]instanceof D&&this[-1].ctrlSeq!=this.ctrlSeq&&this[-1][-1]&&"\\sum "===this[-1][-1].ctrlSeq?this.sum||(this.sum=!0,this.jQ.addClass("sum")):this.limit?(this.limit=!1,this.jQ.removeClass("limit")):this.sum&&(this.sum=!1,this.jQ.removeClass("sum"));if(this.respaced=this[-1]instanceof D&&this[-1].ctrlSeq!=this.ctrlSeq&&!this[-1].respaced){var a=+this.jQ.css("fontSize").slice(0,-2),c=this[-1].jQ.outerWidth(),
e=this.jQ.outerWidth();this.jQ.css({left:(this.limit&&"_"===this.ctrlSeq?-.25:0)-c/a+"em",marginRight:.1-M(e,c)/a+"em"})}else this.limit&&"_"===this.ctrlSeq?this.jQ.css({left:"-.25em",marginRight:""}):this.jQ.css({left:"",marginRight:""});this[1]instanceof D&&this[1].respace();return this}});a.subscript=a._=b(D,"_","sub","_");a.superscript=a.supscript=a["^"]=b(D,"^","sup","**");var l=a.frac=a.dfrac=a.cfrac=a.fraction=g(h,function(a,b){a.ctrlSeq="\\frac";a.htmlTemplate='<span class="fraction non-leaf"><span class="numerator">&0</span><span class="denominator">&1</span><span style="display:inline-block;width:0">&nbsp;</span></span>';
a.textTemplate=["(","/",")"];a.finalizeTree=function(){this.up=this.ends[1].up=this.ends[-1];this.down=this.ends[-1].down=this.ends[1]}}),ia=a.over=x["/"]=g(l,function(a,b){a.createLeftOf=function(a){if(!this.replacedFragment){for(var c=a[-1];c&&!(c instanceof k||c instanceof P||c instanceof L||/^[,;:]$/.test(c.ctrlSeq));)c=c[-1];c instanceof L&&c[1]instanceof D&&(c=c[1],c[1]instanceof D&&c[1].ctrlSeq!=c.ctrlSeq&&(c=c[1]));c!==a[-1]&&(this.replaces(R(c[1]||a.parent.ends[-1],a[-1])),a[-1]=c)}b.createLeftOf.call(this,
a)}}),l=a.sqrt=a["\u221a"]=g(h,function(a,b){a.ctrlSeq="\\sqrt";a.htmlTemplate='<span class="non-leaf"><span class="scaled sqrt-prefix">&radic;</span><span class="non-leaf sqrt-stem">&0</span></span>';a.textTemplate=["sqrt(",")"];a.parser=function(){return J.optBlock.then(function(a){return J.block.map(function(c){var e=ja();e.blocks=[a,c];a.adopt(e,0,0);c.adopt(e,a,0);return e})}).or(b.parser.call(this))};a.redraw=function(){var a=this.ends[1].jQ;F(a.prev(),1,a.innerHeight()/+a.css("fontSize").slice(0,
-2)-.1)}});a.vec=g(h,function(a,b){a.ctrlSeq="\\vec";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&rarr;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["vec(",")"]});var ja=a.nthroot=g(l,function(a,b){a.htmlTemplate='<sup class="nthroot non-leaf">&0</sup><span class="scaled"><span class="sqrt-prefix scaled">&radic;</span><span class="sqrt-stem non-leaf">&1</span></span>';a.textTemplate=["sqrt[","](",")"];a.latex=function(){return"\\sqrt["+this.ends[-1].latex()+
"]{"+this.ends[1].latex()+"}"}});a.dot=g(h,function(a,b){a.ctrlSeq="\\dot";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&middot;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["dot(",")"]});a.ddot=g(h,function(a,b){a.ctrlSeq="\\ddot";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&middot;&nbsp;&middot;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["ddot(",")"]});a.tdot=g(h,function(a,b){a.ctrlSeq="\\tdot";a.htmlTemplate=
'<span class="non-leaf"><span class="vector-prefix">&hellip;</span><span class="vector-stem2">&0</span></span>';a.textTemplate=["tdot(",")"]});a.hat=g(h,function(a,b){a.ctrlSeq="\\hat";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">^</span><span class="vector-stem">&0</span></span>';a.textTemplate=["hat(",")"]});a.check=g(h,function(a,b){a.ctrlSeq="\\check";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&check;</span><span class="vector-stem">&0</span></span>';
a.textTemplate=["check(",")"]});a.grave=g(h,function(a,b){a.ctrlSeq="\\grave";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&grave;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["grave(",")"]});a.acute=g(h,function(a,b){a.ctrlSeq="\\acute";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&acute;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["acute(",")"]});a.tilde=g(h,function(a,b){a.ctrlSeq="\\tilde";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&tilde;</span><span class="vector-stem">&0</span></span>';
a.textTemplate=["tilde(",")"]});a.breve=g(h,function(a,b){a.ctrlSeq="\\breve";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix">&breve;</span><span class="vector-stem">&0</span></span>';a.textTemplate=["breve(",")"]});a.overrightarrow=g(h,function(a,b){a.ctrlSeq="\\overrightarrow";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix right">&rarr;</span><span class="over-arrow">&0</span></span>';a.textTemplate=["overrightarrow(",")"]});a.overleftarrow=g(h,function(a,b){a.ctrlSeq=
"\\overleftarrow";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix left">&larr;</span><span class="over-arrow">&0</span></span>';a.textTemplate=["overleftarrow(",")"]});a.underrightarrow=g(h,function(a,b){a.ctrlSeq="\\underrightarrow";a.htmlTemplate='<span class="non-leaf"><span class="under-arrow">&0</span><span class="vector-prefix right">&rarr;</span></span>';a.textTemplate=["underrightarrow(",")"]});a.underleftarrow=g(h,function(a,b){a.ctrlSeq="\\underleftarrow";a.htmlTemplate=
'<span class="non-leaf"><span class="under-arrow">&0</span><span class="vector-prefix left">&larr;</span></span>';a.textTemplate=["underleftarrow(",")"]});a.overleftrightarrow=g(h,function(a,b){a.ctrlSeq="\\overleftrightarrow";a.htmlTemplate='<span class="non-leaf"><span class="vector-prefix right">&rarr;</span><span class="vector-prefix left">&larr;</span><span class="over-arrow">&0</span></span>';a.textTemplate=["overleftrightarrow(",")"]});a.underleftrightarrow=g(h,function(a,b){a.ctrlSeq="\\underleftrightarrow";
a.htmlTemplate='<span class="non-leaf"><span class="under-arrow">&0</span><span class="vector-prefix right">&rarr;</span><span class="vector-prefix left">&larr;</span></span>';a.textTemplate=["underleftrightarrow(",")"]});var O=g(h,function(a,b){a.init=function(a,c,e,d){b.init.call(this,"\\left"+e,'<span class="non-leaf"><span class="scaled paren">'+a+'</span><span class="non-leaf">&0</span><span class="scaled paren">'+c+"</span></span>",[a,c]);this.end="\\right"+d};a.jQadd=function(){b.jQadd.apply(this,
arguments);var a=this.jQ;this.bracketjQs=a.children(":first").add(a.children(":last"))};a.latex=function(){return this.ctrlSeq+this.ends[-1].latex()+this.end};a.redraw=function(){var a=this.ends[-1].jQ,a=a.outerHeight()/+a.css("fontSize").slice(0,-2);F(this.bracketjQs,M(1+.2*(a-1),1.2),1.05*a)}});a.left=g(h,function(a){a.parser=function(){var a=q.regex,b=q.string,c=q.succeed,e=q.optWhitespace;return e.then(a(/^(?:[([|]|\\\{)/)).then(function(d){"\\"===d.charAt(0)&&(d=d.slice(1));var m=x[d]();return J.map(function(a){m.blocks=
[a];a.adopt(m,0,0)}).then(b("\\right")).skip(e).then(a(/^(?:[\])|]|\\\})/)).then(function(a){return a.slice(-1)!==m.end.slice(-1)?q.fail("open doesn't match close"):c(m)})})}});a.right=g(h,function(a){a.parser=function(){return q.fail("unmatched \\right")}});a.lbrace=x["{"]=b(O,"{","}","\\{","\\}");a.langle=a.lang=b(O,"&lang;","&rang;","\\langle ","\\rangle ");var S=g(O,function(a,b){a.createLeftOf=function(a){a[1]||!a.parent.parent||a.parent.parent.end!==this.end||this.replacedFragment?b.createLeftOf.call(this,
a):a.insRightOf(a.parent.parent)};a.placeCursor=function(a){this.ends[-1].blur();a.insRightOf(this)}});a.rbrace=x["}"]=b(S,"{","}","\\{","\\}");a.rangle=a.rang=b(S,"&lang;","&rang;","\\langle ","\\rangle ");K=function(a,b){a.init=function(a,c){b.init.call(this,a,c,a,c)}};l=g(O,K);a.lparen=x["("]=b(l,"(",")");a.lbrack=a.lbracket=x["["]=b(l,"[","]");K=g(S,K);a.rparen=x[")"]=b(K,"(",")");a.rbrack=a.rbracket=x["]"]=b(K,"[","]");a.lpipe=a.rpipe=x["|"]=g(l,function(a,b){a.init=function(){b.init.call(this,
"|","|")};a.createLeftOf=S.prototype.createLeftOf});var P=x.$=a.text=a.textnormal=a.textrm=a.textup=a.textmd=g(h,function(a,b){a.ctrlSeq="\\text";a.htmlTemplate='<span class="text">&0</span>';a.replaces=function(a){a instanceof R?this.replacedText=a.remove().jQ.text():"string"===typeof a&&(this.replacedText=a)};a.textTemplate=['"','"'];a.parser=function(){var a=this,c=q.string,b=q.regex;return q.optWhitespace.then(c("{")).then(b(/^[^}]*/)).skip(c("}")).map(function(c){a.createBlocks();for(var b=a.ends[-1],
e=0;e<c.length;e+=1)d(c.charAt(e)).adopt(b,b.ends[1],0);return a})};a.createBlocks=function(){this.ends[-1]=this.ends[1]=ka();this.blocks=[this.ends[-1]];this.ends[-1].parent=this};a.finalizeInsert=function(){this.ends[-1].blur=function(){delete this.blur;return this};b.finalizeInsert.call(this)};a.createLeftOf=function(a){b.createLeftOf.call(this,this.cursor=a);if(this.replacedText)for(var c=0;c<this.replacedText.length;c+=1)this.ends[-1].write(a,this.replacedText.charAt(c))}}),ka=g(A,function(a,
b){a.onKey=function(a,c){if("Spacebar"===a||"Shift-Spacebar"===a)return!1};a.deleteOutOf=function(a,c){this.isEmpty()&&c.insRightOf(this.parent)};a.write=function(a,c,b){b&&b.remove();if("$"!==c){var e;"<"===c?e="&lt;":">"===c&&(e="&gt;");d(c,e).createLeftOf(a)}else this.isEmpty()?(a.insRightOf(this.parent).backspace(),d("\\$","$").createLeftOf(a)):a[1]?a[-1]?(c=P(),c.replaces(R(a[1],this.ends[1])),a.insRightOf(this.parent),c.adopt=function(){delete this.adopt;this.adopt.apply(this,arguments);this[-1]=
0},c.createLeftOf(a),c[-1]=this.parent,a.insLeftOf(c)):a.insLeftOf(this.parent):a.insRightOf(this.parent);return!1};a.blur=function(){this.jQ.removeClass("hasCursor");if(this.isEmpty()){var a=this.parent,c=a.cursor;c.parent===this?this.jQ.addClass("empty"):(c.hide(),a.remove(),c[1]===a?c[1]=a[1]:c[-1]===a&&(c[-1]=a[-1]),c.show().parent.bubble("redraw"))}return this};a.focus=function(){b.focus.call(this);var a=this.parent;if(a[1].ctrlSeq===a.ctrlSeq){var c=this,e=a.cursor,a=a[1].ends[-1];a.eachChild(function(a){a.parent=
c;a.jQ.appendTo(c.jQ)});this.ends[1]?this.ends[1][1]=a.ends[-1]:this.ends[-1]=a.ends[-1];a.ends[-1][-1]=this.ends[1];this.ends[1]=a.ends[1];a.parent.remove();e[-1]?e.insRightOf(e[-1]):e.insAtLeftEnd(this);e.parent.bubble("redraw")}else a[-1].ctrlSeq===a.ctrlSeq&&(e=a.cursor,e[-1]?a[-1].ends[-1].focus():e.insAtRightEnd(a[-1].ends[-1]));return this}});a.em=a.italic=a.italics=a.emph=a.textit=a.textsl=I("\\textit","i",'class="text"');a.strong=a.bold=a.textbf=I("\\textbf","b",'class="text"');a.sf=a.textsf=
I("\\textsf","span",'class="sans-serif text"');a.tt=a.texttt=I("\\texttt","span",'class="monospace text"');a.textsc=I("\\textsc","span",'style="font-variant:small-caps" class="text"');a.uppercase=I("\\uppercase","span",'style="text-transform:uppercase" class="text"');a.lowercase=I("\\lowercase","span",'style="text-transform:lowercase" class="text"');x["\\"]=g(h,function(a,b){a.ctrlSeq="\\";a.replaces=function(a){this._replacedFragment=a.disown();this.isEmpty=function(){return!1}};a.htmlTemplate='<span class="latex-command-input non-leaf">\\<span>&0</span></span>';
a.textTemplate=["\\"];a.createBlocks=function(){b.createBlocks.call(this);this.ends[-1].focus=function(){this.parent.jQ.addClass("hasCursor");this.isEmpty()&&this.parent.jQ.removeClass("empty");return this};this.ends[-1].blur=function(){this.parent.jQ.removeClass("hasCursor");this.isEmpty()&&this.parent.jQ.addClass("empty");return this}};a.createLeftOf=function(a){b.createLeftOf.call(this,a);this.cursor=a.insAtRightEnd(this.ends[-1]);if(this._replacedFragment){var c=this.jQ[0];this.jQ=this._replacedFragment.jQ.addClass("blur").bind("mousedown mousemove",
function(a){r(a.target=c).trigger(a);return!1}).insertBefore(this.jQ).add(this.jQ)}this.ends[-1].write=function(a,c,b){b&&b.remove();c.match(/[a-z]/i)?d(c).createLeftOf(a):(this.parent.renderCommand(),"\\"===c&&this.isEmpty()||this.parent.parent.write(a,c))}};a.latex=function(){return"\\"+this.ends[-1].latex()+" "};a.onKey=function(a,c){if("Tab"===a||"Enter"===a||"Spacebar"===a)return this.renderCommand(),c.preventDefault(),!1};a.renderCommand=function(){this.jQ=this.jQ.last();this.remove();this[1]?
this.cursor.insLeftOf(this[1]):this.cursor.insAtRightEnd(this.parent);var a=this.ends[-1].latex();a||(a="backslash");this.cursor.insertCmd(a,this._replacedFragment)}});l=a.binom=a.binomial=g(h,function(a,b){a.ctrlSeq="\\binom";a.htmlTemplate='<span class="paren scaled">(</span><span class="non-leaf"><span class="array non-leaf"><span>&0</span><span>&1</span></span></span><span class="paren scaled">)</span>';a.textTemplate=["choose(",",",")"];a.redraw=function(){var a=this.jQ.eq(1),a=a.outerHeight()/
+a.css("fontSize").slice(0,-2),c=this.jQ.filter(".paren");F(c,M(1+.2*(a-1),1.2),1.05*a)}});a.edenCmdStackTwo=g(h,function(a,b){a.ctrlSeq="\\edenCmdStackTwo";a.htmlTemplate='<span class="paren scaled" style="vertical-align:sub;">{</span><span class="non-leaf"><span class="array non-leaf"><span style="min-width: 20px;">&0</span><span style="min-width: 20px;">&1</span></span></span><span class="paren scaled"></span>';a.textTemplate=["choose(",",",")"];a.redraw=function(){var a=this.jQ.eq(1),a=a.outerHeight()/
+a.css("fontSize").slice(0,-2),c=this.jQ.filter(".paren");F(c,M(1+.2*(a-1),1.2),1.05*a)};a.latex=function(){return("\\left\\{\\begin{array}{l}"+this.foldChildren([],function(a,c){return a+(c.latex()||" ")+"\\\\"})+"end{array}\\right. ").replace("\\end","end")}});a.edenCmdStackThree=g(h,function(a,b){a.ctrlSeq="\\edenCmdStackThree";a.htmlTemplate='<span class="paren scaled">{</span><span class="non-leaf"><span class="array non-leaf"><span style="min-width: 20px;">&0</span><span style="min-width: 20px;">&1</span><span style="min-width: 20px;">&2</span></span></span><span class="paren scaled"></span>';
a.textTemplate=["choose(",",",",",")"];a.redraw=function(){var a=this.jQ.eq(1),a=a.outerHeight()/+a.css("fontSize").slice(0,-2),c=this.jQ.filter(".paren");F(c,M(1+.2*(a-1),1.2),1.05*a)};a.latex=function(){return("\\left\\{\\begin{array}{l}"+this.foldChildren([],function(a,c){return a+(c.latex()||" ")+"\\\\"})+"end{array}\\right. ").replace("\\end","end")}});a.edenCmdBinom=g(h,function(a,b){a.ctrlSeq="\\edenCmdBinom";a.htmlTemplate='<span class="paren scaled" style="vertical-align:sub;">(</span><span class="non-leaf"><span class="array non-leaf"><span style="min-width: 20px;">&0</span><span style="min-width: 20px;">&1</span></span></span><span class="paren scaled" style="vertical-align:sub;">)</span>';
a.textTemplate=["choose(",",",")"];a.redraw=function(){var a=this.jQ.eq(1),a=a.outerHeight()/+a.css("fontSize").slice(0,-2),c=this.jQ.filter(".paren");F(c,M(1+.2*(a-1),1.2),1.05*a)};a.latex=function(){return("\\left(\\begin{array}{l}"+this.foldChildren([],function(a,c){return a+(c.latex()||" ")+"\\\\"})+"end{array}\\right)").replace("\\end","end")}});a.choose=g(l,function(a){a.createLeftOf=ia.prototype.createLeftOf});a.vector=g(h,function(a,b){a.ctrlSeq="\\vector";a.htmlTemplate='<span class="array"><span>&0</span></span>';
a.latex=function(){return"\\begin{matrix}"+this.foldChildren([],function(a,c){a.push(c.latex());return a}).join("\\\\")+"\\end{matrix}"};a.text=function(){return"["+this.foldChildren([],function(a,c){a.push(c.text());return a}).join()+"]"};a.placeCursor=function(a){this.cursor=a.appendTo(this.firstChild)};a.createLeftOf=function(a){b.createLeftOf.call(this,this.cursor=a)};a.onKey=function(a,c){var b=this.cursor.parent;if(b.parent===this){if("Enter"===a){var e=A();e.parent=this;e.jQ=r("<span></span>").attr("mathquill-block-id",
e.id).insertAfter(b.jQ);b[1]?b[1][-1]=e:this.ends[1]=e;e[1]=b[1];b[1]=e;e[-1]=b;this.bubble("redraw").cursor.insAtRightEnd(e);c.preventDefault();return!1}if("Tab"===a&&!b[1]){if(b.isEmpty()){if(b[-1])return this.cursor.insRightOf(this),delete b[-1][1],this.ends[1]=b[-1],b.jQ.remove(),this.bubble("redraw"),c.preventDefault(),!1;return}e=A();e.parent=this;e.jQ=r("<span></span>").attr("mathquill-block-id",e.id).appendTo(this.jQ);this.ends[1]=e;b[1]=e;e[-1]=b;this.bubble("redraw").cursor.insAtRightEnd(e);
c.preventDefault();return!1}if(8===c.which){if(b.isEmpty())return b[-1]?(this.cursor.insAtRightEnd(b[-1]),b[-1][1]=b[1]):(this.cursor.insLeftOf(this),this.ends[-1]=b[1]),b[1]?b[1][-1]=b[-1]:this.ends[1]=b[-1],b.jQ.remove(),this.isEmpty()?this.cursor.deleteForward():this.bubble("redraw"),c.preventDefault(),!1;if(!this.cursor[-1])return c.preventDefault(),!1}}}});a.editable=g(X,function(a,b){a.init=function(){h.prototype.init.call(this,"\\editable")};a.jQadd=function(){b.jQadd.apply(this,arguments);
var a=this.ends[-1].disown(),c=this.jQ.children().detach();this.ends[-1]=this.ends[1]=N();this.blocks=[this.ends[-1]];this.ends[-1].parent=this;aa(this.jQ,this.ends[-1],!1,!0);this.cursor=this.ends[-1].cursor;a.children().adopt(this.ends[-1],0,0);c.appendTo(this.ends[-1].jQ);this.ends[-1].cursor.insAtRightEnd(this.ends[-1])};a.latex=function(){return this.ends[-1].latex()};a.text=function(){return this.ends[-1].text()}});a.f=b(C,"f",'<var class="florin">&fnof;</var><span style="display:inline-block;width:0">&nbsp;</span>');
var v=g(C,function(a,b){a.init=function(a,c){b.init.call(this,a,"<var>"+(c||a)+"</var>")};a.text=function(){var a=this.ctrlSeq;!this[-1]||this[-1]instanceof v||this[-1]instanceof k||(a="*"+a);!this[1]||this[1]instanceof k||"^"===this[1].ctrlSeq||(a+="*");return a}}),d=g(C,function(a,b){a.init=function(a,c){b.init.call(this,a,"<span>"+(c||a)+"</span>")}});x[" "]=b(d,"\\:"," ");a.prime=x["'"]=b(d,"'","&prime;");l=g(C,function(a,b){a.init=function(a,c){b.init.call(this,a,'<span class="nonSymbola">'+
(c||a)+"</span>")}});a["@"]=l;a["&"]=b(l,"\\&","&amp;");a["%"]=b(l,"\\%","%");a.alpha=a.beta=a.gamma=a.delta=a.zeta=a.eta=a.theta=a.iota=a.kappa=a.mu=a.nu=a.xi=a.rho=a.sigma=a.tau=a.chi=a.psi=a.omega=g(v,function(a,b){a.init=function(a){b.init.call(this,"\\"+a+" ","&"+a+";")}});a.phi=b(v,"\\phi ","&#981;");a.img=b(v,"\\img dynamic set",'<img src=""></img>');a.phiv=a.varphi=b(v,"\\varphi ","&phi;");a.epsilon=b(v,"\\epsilon ","&#1013;");a.epsiv=a.varepsilon=b(v,"\\varepsilon ","&epsilon;");a.piv=a.varpi=
b(v,"\\varpi ","&piv;");a.sigmaf=a.sigmav=a.varsigma=b(v,"\\varsigma ","&sigmaf;");a.thetav=a.vartheta=a.thetasym=b(v,"\\vartheta ","&thetasym;");a.upsilon=a.upsi=b(v,"\\upsilon ","&upsilon;");a.gammad=a.Gammad=a.digamma=b(v,"\\digamma ","&#989;");a.kappav=a.varkappa=b(v,"\\varkappa ","&#1008;");a.rhov=a.varrho=b(v,"\\varrho ","&#1009;");a.pi=a["\u03c0"]=b(l,"\\pi ","&pi;");a.lambda=b(l,"\\lambda ","&lambda;");a.Upsilon=a.Upsi=a.upsih=a.Upsih=b(C,"\\Upsilon ",'<var style="font-family: serif">&upsih;</var>');
a.Gamma=a.Delta=a.Theta=a.Lambda=a.Xi=a.Pi=a.Sigma=a.Phi=a.Psi=a.Omega=a.forall=g(d,function(a,b){a.init=function(a){b.init.call(this,"\\"+a+" ","&"+a+";")}});l=g(h,function(a){a.init=function(a){this.latex=a};a.createLeftOf=function(a){a.writeLatex(this.latex)};a.parser=function(){var a=J.parse(this.latex).children();return q.succeed(a)}});a["\u00b9"]=b(l,"^1");a["\u00b2"]=b(l,"^2");a["\u00b3"]=b(l,"^3");a["\u00bc"]=b(l,"\\frac14");a["\u00bd"]=b(l,"\\frac12");a["\u00be"]=b(l,"\\frac34");var k=g(C,
function(a,b){a.init=function(a,c,e){b.init.call(this,a,'<span class="binary-operator">'+c+"</span>",e)}}),l=g(k,function(a){a.init=d.prototype.init;a.respace=function(){this.jQ[0].className=this[-1]?this[-1]instanceof k&&this[1]&&!(this[1]instanceof k)?"unary-operator":"binary-operator":"";return this}});a["+"]=b(l,"+","+");a["\u2013"]=a["-"]=b(l,"-","&minus;");a["\u00b1"]=a.pm=a.plusmn=a.plusminus=b(l,"\\pm ","&plusmn;");a.mp=a.mnplus=a.minusplus=b(l,"\\mp ","&#8723;");x["*"]=a.sdot=a.cdot=b(k,
"\\cdot ","&middot;");a["="]=b(k,"=","=");a["<"]=b(k,"<","&lt;");a[">"]=b(k,">","&gt;");a.notin=a.sim=a.cong=a.equiv=a.oplus=a.otimes=g(k,function(a,b){a.init=function(a){b.init.call(this,"\\"+a+" ","&"+a+";")}});a.times=b(k,"\\times ","&times;","[x]");a["\u00f7"]=a.div=a.divide=a.divides=b(k,"\\div ","&divide;","[/]");a["\u2260"]=a.ne=a.neq=b(k,"\\ne ","&ne;");a.ast=a.star=a.loast=a.lowast=b(k,"\\ast ","&lowast;");a.therefor=a.therefore=b(k,"\\therefore ","&there4;");a.cuz=a.because=b(k,"\\because ",
"&#8757;");a.prop=a.propto=b(k,"\\propto ","&prop;");a["\u2248"]=a.asymp=a.approx=b(k,"\\approx ","&asymp;");a.lt=b(k,"<","&lt;");a.gt=b(k,">","&gt;");a["\u2264"]=a.le=a.leq=b(k,"\\le ","&le;");a["\u2265"]=a.ge=a.geq=b(k,"\\ge ","&ge;");a.isin=a["in"]=b(k,"\\in ","&isin;");a.ni=a.contains=b(k,"\\ni ","&ni;");a.notni=a.niton=a.notcontains=a.doesnotcontain=b(k,"\\not\\ni ","&#8716;");a.sub=a.subset=b(k,"\\subset ","&sub;");a.sup=a.supset=a.superset=b(k,"\\supset ","&sup;");a.nsub=a.notsub=a.nsubset=
a.notsubset=b(k,"\\not\\subset ","&#8836;");a.nsup=a.notsup=a.nsupset=a.notsupset=a.nsuperset=a.notsuperset=b(k,"\\not\\supset ","&#8837;");a.sube=a.subeq=a.subsete=a.subseteq=b(k,"\\subseteq ","&sube;");a.supe=a.supeq=a.supsete=a.supseteq=a.supersete=a.superseteq=b(k,"\\supseteq ","&supe;");a.nsube=a.nsubeq=a.notsube=a.notsubeq=a.nsubsete=a.nsubseteq=a.notsubsete=a.notsubseteq=b(k,"\\not\\subseteq ","&#8840;");a.nsupe=a.nsupeq=a.notsupe=a.notsupeq=a.nsupsete=a.nsupseteq=a.notsupsete=a.notsupseteq=
a.nsupersete=a.nsuperseteq=a.notsupersete=a.notsuperseteq=b(k,"\\not\\supseteq ","&#8841;");var L=g(C,function(a,b){a.init=function(a,c){b.init.call(this,a,"<big>"+c+"</big>")}});a["\u2211"]=a.sum=a.summation=b(L,"\\sum ","&sum;");a["\u220f"]=a.prod=a.product=b(L,"\\prod ","&prod;");a.coprod=a.coproduct=b(L,"\\coprod ","&#8720;");a["\u222b"]=a["int"]=a.integral=b(L,"\\int ","&int;");a.oint=b(L,"\\oint ","&#8750;");a.N=a.naturals=a.Naturals=b(d,"\\mathbb{N}","&#8469;");a.P=a.primes=a.Primes=a.projective=
a.Projective=a.probability=a.Probability=b(d,"\\mathbb{P}","&#8473;");a.Z=a.integers=a.Integers=b(d,"\\mathbb{Z}","&#8484;");a.Q=a.rationals=a.Rationals=b(d,"\\mathbb{Q}","&#8474;");a.R=a.reals=a.Reals=b(d,"\\mathbb{R}","&#8477;");a.C=a.complex=a.Complex=a.complexes=a.Complexes=a.complexplane=a.Complexplane=a.ComplexPlane=b(d,"\\mathbb{C}","&#8450;");a.H=a.Hamiltonian=a.quaternions=a.Quaternions=b(d,"\\mathbb{H}","&#8461;");a.quad=a.emsp=b(d,"\\quad ","    ");a.qquad=b(d,"\\qquad ","        ");a.diamond=
b(d,"\\diamond ","&#9671;");a.bigtriangleup=b(d,"\\bigtriangleup ","&#9651;");a.ominus=b(d,"\\ominus ","&#8854;");a.uplus=b(d,"\\uplus ","&#8846;");a.bigtriangledown=b(d,"\\bigtriangledown ","&#9661;");a.sqcap=b(d,"\\sqcap ","&#8851;");a.triangleleft=b(d,"\\triangleleft ","&#8882;");a.sqcup=b(d,"\\sqcup ","&#8852;");a.triangleright=b(d,"\\triangleright ","&#8883;");a.odot=b(d,"\\odot ","&#8857;");a.bigcirc=b(d,"\\bigcirc ","&#9711;");a.dagger=b(d,"\\dagger ","&#0134;");a.ddagger=b(d,"\\ddagger ",
"&#135;");a.wr=b(d,"\\wr ","&#8768;");a.amalg=b(d,"\\amalg ","&#8720;");a.percent=b(d,"\\percent ","&#37;");a.factorial=b(d,"!","!");a.models=b(d,"\\models ","&#8872;");a.prec=b(d,"\\prec ","&#8826;");a.succ=b(d,"\\succ ","&#8827;");a.preceq=b(d,"\\preceq ","&#8828;");a.succeq=b(d,"\\succeq ","&#8829;");a.simeq=b(d,"\\simeq ","&#8771;");a.mid=b(d,"\\mid ","&#8739;");a.ll=b(d,"\\ll ","&#8810;");a.gg=b(d,"\\gg ","&#8811;");a.parallel=b(d,"\\parallel ","&#8741;");a.bowtie=b(d,"\\bowtie ","&#8904;");
a.sqsubset=b(d,"\\sqsubset ","&#8847;");a.sqsupset=b(d,"\\sqsupset ","&#8848;");a.smile=b(d,"\\smile ","&#8995;");a.sqsubseteq=b(d,"\\sqsubseteq ","&#8849;");a.sqsupseteq=b(d,"\\sqsupseteq ","&#8850;");a.doteq=b(d,"\\doteq ","&#8784;");a.frown=b(d,"\\frown ","&#8994;");a.vdash=b(d,"\\vdash ","&#8870;");a.dashv=b(d,"\\dashv ","&#8867;");a.overequal=b(d,"\u2266 ","&#8806;");a.approximatelyequal=b(d,"\u2252 ","&#8786;");a.nless=b(d,"\\nless ","&#8814;");a.nleqslant=b(d,"\\nleqslant ","&#8816;");a.ngtr=
b(d,"\\ngtr ","&#8815;");a.ngeqslant=b(d,"\\ngeqslant ","&#8817;");a.lnsim=b(d,"\\lnsim ","&#8820;");a.gnsim=b(d,"\\gnsim ","&#8821;");a.nparallel=b(d,"\\nparallel ","&#8742;");a.nvDash=b(d,"\\nvDash ","&#8877;");a.nVDash=b(d,"\\nVDash ","&#8879;");a.nMember=b(d,"\u220c ","&#8716;");a.longleftarrow=b(d,"\\longleftarrow ","&#8592;");a.longrightarrow=b(d,"\\longrightarrow ","&#8594;");a.Longleftarrow=b(d,"\\Longleftarrow ","&#8656;");a.Longrightarrow=b(d,"\\Longrightarrow ","&#8658;");a.longleftrightarrow=
b(d,"\\longleftrightarrow ","&#8596;");a.updownarrow=b(d,"\\updownarrow ","&#8597;");a.Longleftrightarrow=b(d,"\\Longleftrightarrow ","&#8660;");a.Updownarrow=b(d,"\\Updownarrow ","&#8661;");a.mapsto=b(d,"\\mapsto ","&#8614;");a.nearrow=b(d,"\\nearrow ","&#8599;");a.hookleftarrow=b(d,"\\hookleftarrow ","&#8617;");a.hookrightarrow=b(d,"\\hookrightarrow ","&#8618;");a.searrow=b(d,"\\searrow ","&#8600;");a.leftharpoonup=b(d,"\\leftharpoonup ","&#8636;");a.rightharpoonup=b(d,"\\rightharpoonup ","&#8640;");
a.swarrow=b(d,"\\swarrow ","&#8601;");a.leftharpoondown=b(d,"\\leftharpoondown ","&#8637;");a.rightharpoondown=b(d,"\\rightharpoondown ","&#8641;");a.nwarrow=b(d,"\\nwarrow ","&#8598;");a.ldots=b(d,"\\ldots ","&#8230;");a.cdots=b(d,"\\cdots ","&#8943;");a.vdots=b(d,"\\vdots ","&#8942;");a.ddots=b(d,"\\ddots ","&#8944;");a.surd=b(d,"\\surd ","&#8730;");a.triangle=b(d,"\\triangle ","&#9653;");a.ell=b(d,"\\ell ","&#8467;");a.top=b(d,"\\top ","&#8868;");a.flat=b(d,"\\flat ","&#9837;");a.natural=b(d,"\\natural ",
"&#9838;");a.sharp=b(d,"\\sharp ","&#9839;");a.wp=b(d,"\\wp ","&#8472;");a.bot=b(d,"\\bot ","&#8869;");a.clubsuit=b(d,"\\clubsuit ","&#9827;");a.diamondsuit=b(d,"\\diamondsuit ","&#9826;");a.heartsuit=b(d,"\\heartsuit ","&#9825;");a.spadesuit=b(d,"\\spadesuit ","&#9824;");a.bigcap=b(d,"\\bigcap ","&#8745;");a.bigcup=b(d,"\\bigcup ","&#8746;");a.bigsqcup=b(d,"\\bigsqcup ","&#8852;");a.bigvee=b(d,"\\bigvee ","&#8744;");a.bigwedge=b(d,"\\bigwedge ","&#8743;");a.bigodot=b(d,"\\bigodot ","&#8857;");a.bigotimes=
b(d,"\\bigotimes ","&#8855;");a.bigoplus=b(d,"\\bigoplus ","&#8853;");a.biguplus=b(d,"\\biguplus ","&#8846;");a.lfloor=b(d,"\\lfloor ","&#8970;");a.rfloor=b(d,"\\rfloor ","&#8971;");a.lceil=b(d,"\\lceil ","&#8968;");a.rceil=b(d,"\\rceil ","&#8969;");a.slash=b(d,"\\slash ","&#47;");a.opencurlybrace=b(d,"\\opencurlybrace ","&#123;");a.closecurlybrace=b(d,"\\closecurlybrace ","&#125;");a.caret=b(d,"\\caret ","^");a.underscore=b(d,"\\underscore ","_");a.backslash=b(d,"\\backslash ","\\");a.vert=b(d,"|");
a.perp=a.perpendicular=b(d,"\u22a5 ","&perp;");a.nabla=a.del=b(d,"\\nabla ","&nabla;");a.hbar=b(d,"\\hbar ","&#8463;");a.AA=a.Angstrom=a.angstrom=b(d,"\\text\\AA ","&#8491;");a.ring=a.circ=a.circle=b(d,"\\circ ","&#8728;");a.bull=a.bullet=b(d,"\\bullet ","&bull;");a.setminus=a.smallsetminus=b(d,"\\setminus ","&#8726;");a.not=b(C,"\\not ",'<span class="not">/</span>');a["\u00ac"]=a.neg=b(d,"\\neg ","&not;");a["\u2026"]=a.dots=a.ellip=a.hellip=a.ellipsis=a.hellipsis=b(d,"\\dots ","&hellip;");a.converges=
a.darr=a.dnarr=a.dnarrow=a.downarrow=b(d,"\\downarrow ","&darr;");a.dArr=a.dnArr=a.dnArrow=a.Downarrow=b(d,"\\Downarrow ","&dArr;");a.diverges=a.uarr=a.uparrow=b(d,"\\uparrow ","&uarr;");a.uArr=a.Uparrow=b(d,"\\Uparrow ","&uArr;");a.to=b(k,"\\to ","&rarr;");a.rarr=a.rightarrow=b(d,"\\rightarrow ","&rarr;");a.implies=b(k,"\\Rightarrow ","&rArr;");a.rArr=a.Rightarrow=b(d,"\\Rightarrow ","&rArr;");a.gets=b(k,"\\gets ","&larr;");a.larr=a.leftarrow=b(d,"\\leftarrow ","&larr;");a.impliedby=b(k,"\\Leftarrow ",
"&lArr;");a.lArr=a.Leftarrow=b(d,"\\Leftarrow ","&lArr;");a.harr=a.lrarr=a.leftrightarrow=b(d,"\\leftrightarrow ","&harr;");a.iff=b(k,"\\Leftrightarrow ","&hArr;");a.hArr=a.lrArr=a.Leftrightarrow=b(d,"\\Leftrightarrow ","&hArr;");a.Re=a.Real=a.real=b(d,"\\Re ","&real;");a.Im=a.imag=a.image=a.imagin=a.imaginary=a.Imaginary=b(d,"\\Im ","&image;");a.part=a.partial=b(d,"\\partial ","&part;");a.inf=a.infin=a.infty=a.infinity=b(d,"\\infty ","&infin;");a.alef=a.alefsym=a.aleph=a.alephsym=b(d,"\\aleph ",
"&alefsym;");a.xist=a.xists=a.exist=a.exists=b(d,"\\exists ","&exist;");a.and=a.land=a.wedge=b(d,"\\wedge ","&and;");a.or=a.lor=a.vee=b(d,"\\vee ","&or;");a.o=a.O=a.empty=a.emptyset=a.oslash=a.Oslash=a.nothing=a.varnothing=b(k,"\\varnothing ","&empty;");a.cup=a.union=b(k,"\\cup ","&cup;");a.cap=a.intersect=a.intersection=b(k,"\\cap ","&cap;");a.deg=a.degree=b(d,"^{\\circ} ","&deg;");a.ang=a.angle=b(d,"\\angle ","&ang;");a.mho=g(C,function(a,b){a.init=function(a,c){a="mho";b.init.call(this,"\\"+a+
" ","<span style=\"font-family:'Times New Roman';\">&#433;</span>")}});var da=g(C,function(a,b){a.init=function(a){b.init.call(this,"\\"+a+" ","<span>"+a+"</span>")};a.respace=function(){this.jQ[0].className=this[1]instanceof D||this[1]instanceof O?"":"non-italicized-function"}});a.ln=a.lg=a.log=a.span=a.proj=a.det=a.dim=a.min=a.max=a.mod=a.lcm=a.gcd=a.gcf=a.hcf=a.lim=da;(function(){var b="sin cos tan sec cosec csc cotan cot".split(" "),d;for(d in b)a[b[d]]=a[b[d]+"h"]=a["a"+b[d]]=a["arc"+b[d]]=a["a"+
b[d]+"h"]=a["arc"+b[d]+"h"]=da})();var J=function(){function b(a){for(var c=a[0]||A(),d=1;d<a.length;d+=1)a[d].children().adopt(c,c.ends[1],0);return c}var g=q.string,f=q.regex,c=q.any,n=q.optWhitespace,G=q.succeed,m=q.fail,u=q.letter.map(v),h=f(/^[^${}\\_^]/).map(d),f=f(/^[^\\a-eg-zA-Z]/).or(g("\\").then(f(/^[a-z]+/i).or(f(/^\s+/).result(" ")).or(c))).then(function(c){var b=a[c];return b?b(c).parser():m("unknown command: \\"+c)}).or(u).or(h),c=g("{").then(function(){return k}).skip(g("}")),f=n.then(c.or(f.map(function(a){var c=
A();a.adopt(c,0,0);return c}))),k=f.many().map(b).skip(n),g=g("[").then(f.then(function(a){return"]"!==a.join("latex")?G(a):m()}).many().map(b).skip(n)).skip(g("]")),n=k;n.block=f;n.optBlock=g;return n}(),fa=g(V,function(b){function d(a,b){a.clearSelection().show();if(a[1][b])a.insAtLeftEnd(a[1][b]);else if(a[-1][b])a.insAtRightEnd(a[-1][b]);else{var e=a.parent;do{var g=e[b];if(g&&("function"===typeof g&&(g=e[b](a)),!1===g||g instanceof A)){a.upDownCache[e.id]=V(a.parent,a[-1],a[1]);g instanceof A&&
((e=a.upDownCache[g.id])?e[1]?a.insLeftOf(e[1]):a.insAtRightEnd(e.parent):(e=f(a).left,a.insAtRightEnd(g),a.seekHoriz(e,g)));break}e=e.parent.parent}while(e)}return a}function f(a){var b=a.jQ.removeClass("cursor").offset();a.jQ.addClass("cursor");return b}b.init=function(a){this.parent=this.root=a;var b=this.jQ=this._jQ=r('<span class="cursor">&#8203;</span>');this.blink=function(){b.toggleClass("blink")};this.upDownCache={}};b.show=function(){this.jQ=this._jQ.removeClass("blink");"intervalId"in this?
clearInterval(this.intervalId):(this[1]?this.selection&&this.selection.ends[-1][-1]===this[-1]?this.jQ.insertBefore(this.selection.jQ):this.jQ.insertBefore(this[1].jQ.first()):this.jQ.appendTo(this.parent.jQ),this.parent.focus());this.intervalId=setInterval(this.blink,500);return this};b.hide=function(){"intervalId"in this&&clearInterval(this.intervalId);delete this.intervalId;this.jQ.detach();this.jQ=r();return this};b.withDirInsertAt=function(a,b,d,e){var f=this.parent;this.parent=b;this[a]=d;this[-a]=
e;f.blur()};b.insDirOf=function(a,b){E(a);this.withDirInsertAt(a,b.parent,b[a],b);this.parent.jQ.addClass("hasCursor");this.jQ.insDirOf(a,b.jQ);"_"==b.ctrlSeq?"^"==b[a].ctrlSeq&&(-1==a?this.moveLeft():this.moveRight()):"^"==b.ctrlSeq&&"_"==b[a].ctrlSeq&&(-1==a?this.moveLeft():this.moveRight());return this};b.insLeftOf=function(a){return this.insDirOf(-1,a)};b.insRightOf=function(a){return this.insDirOf(1,a)};b.insAtDirEnd=function(a,b){E(a);this.withDirInsertAt(a,b,0,b.ends[a]);-1===a&&b.textarea?
this.jQ.insDirOf(-a,b.textarea):this.jQ.insAtDirEnd(a,b.jQ);b.focus();return this};b.insAtLeftEnd=function(a){return this.insAtDirEnd(-1,a)};b.insAtRightEnd=function(a){return this.insAtDirEnd(1,a)};b.hopDir=function(a){E(a);this.jQ.insDirOf(a,this[a].jQ);this[-a]=this[a];this[a]=this[a][a];return this};b.hopLeft=function(){return this.hopDir(-1)};b.hopRight=function(){return this.hopDir(1)};b.moveDirWithin=function(a,b){E(a);this[a]?this[a].ends[-a]?this.insAtDirEnd(-a,this[a].ends[-a]):this.hopDir(a):
this.parent!==b&&(this.parent[a]?this.insAtDirEnd(-a,this.parent[a]):this.insDirOf(a,this.parent.parent))};b.moveLeftWithin=function(a){return this.moveDirWithin(-1,a)};b.moveRightWithin=function(a){return this.moveDirWithin(1,a)};b.moveDir=function(a){E(a);this.upDownCache={};this.selection?this.insDirOf(a,this.selection.ends[a]).clearSelection():this.moveDirWithin(a,this.root);return this.show()};b.moveLeft=function(){return this.moveDir(-1)};b.moveRight=function(){return this.moveDir(1)};b.moveUp=
function(){return d(this,"up")};b.moveDown=function(){return d(this,"down")};b.seek=function(a,b,d){this.upDownCache={};var e,f=this.clearSelection().show();if(a.hasClass("empty"))return f.insAtLeftEnd(p[a.attr("mathquill-block-id")]),f;d=p[a.attr("mathquill-command-id")];if(d instanceof C)return a.outerWidth()>2*(b-a.offset().left)?f.insLeftOf(d):f.insRightOf(d),f;d||(e=p[a.attr("mathquill-block-id")],e||(a=a.parent(),d=p[a.attr("mathquill-command-id")],d||(e=p[a.attr("mathquill-block-id")],e||(e=
f.root))));d?f.insRightOf(d):f.insAtRightEnd(e);return f.seekHoriz(b,f.root)};b.seekHoriz=function(a,b){var d=f(this).left-a,e;do this.moveLeftWithin(b),e=d,d=f(this).left-a;while(0<d&&(this[-1]||this.parent!==b));30>a?-d>e&&this.moveRightWithin(b):this.moveRightWithin(b);return this};b.writeLatex=function(a){this.upDownCache={};this.show().deleteSelection();var b=q.all;if(a=J.skip(q.eof).or(b.result(!1)).parse(a))a.children().adopt(this.parent,this[-1],this[1]),p.jQize(a.join("html")).insertBefore(this.jQ),
this[-1]=a.ends[1],a.finalizeInsert(),this.parent.bubble("redraw");return this.hide()};b.write=function(a){var b=this.prepareWrite();return this.insertCh(a,b)};b.insertCh=function(a,b){this.parent.write(this,a,b);return this};b.insertCmd=function(b,d){var e=a[b];e?(e=e(b),d&&e.replaces(d),e.createLeftOf(this)):(e=P(),e.replaces(b),e.ends[-1].focus=function(){delete this.focus;return this},e.createLeftOf(this),this.insRightOf(e),d&&d.remove());return this};b.unwrapGramp=function(){var a=this.parent.parent,
b=a.parent,d=a[1],e=a[-1];a.disown().eachChild(function(f){f.isEmpty()||(f.children().adopt(b,e,d).each(function(b){b.jQ.insertBefore(a.jQ.first())}),e=f.ends[1])});if(!this[1])if(this[-1])this[1]=this[-1][1];else for(;!this[1];)if(this.parent=this.parent[1])this[1]=this.parent.ends[-1];else{this[1]=a[1];this.parent=b;break}this[1]?this.insLeftOf(this[1]):this.insAtRightEnd(b);a.jQ.remove();a[-1]&&a[-1].respace();a[1]&&a[1].respace()};b.deleteDir=function(a){E(a);this.upDownCache={};this.show();if(!this.deleteSelection())if(this[a])this[a].isEmpty()?
this[a]=this[a].remove()[a]:this.selectDir(a);else if(this.parent!==this.root){if(this.parent.parent.isEmpty())return this.insDirOf(-a,this.parent.parent).deleteDir(a);this.unwrapGramp()}this[-1]&&this[-1].respace();this[1]&&this[1].respace();this.parent.bubble("redraw");return this};b.backspace=function(){return this.deleteDir(-1)};b.deleteForward=function(){return this.deleteDir(1)};b.selectFrom=function(a){var b=this,d=a;a:for(;;){for(var e=this;e!==b.parent.parent;e=e.parent.parent)if(e.parent===
d.parent){a=e;break a}for(e=a;e!==d.parent.parent;e=e.parent.parent)if(b.parent===e.parent){a=b;d=e;break a}b.parent.parent&&(b=b.parent.parent);d.parent.parent&&(d=d.parent.parent)}var f;if(a[1]!==d){for(b=a;b;b=b[1])if(b===d[-1]){f=!0;break}f||(f=d,d=a,a=f)}this.hide().selection=ea(a[-1][1]||a.parent.ends[-1],d[1][-1]||d.parent.ends[1]);this.insRightOf(d[1][-1]||d.parent.ends[1]);this.root.selectionChanged()};b.selectDir=function(a){E(a);this.upDownCache={};if(this.selection)if(this.selection.ends[a]===
this[-a])this[a]?this.hopDir(a).selection.extendDir(a):this.parent!==this.root&&this.insDirOf(a,this.parent.parent).selection.levelUp();else{this.hopDir(a);if(this.selection.ends[a]===this.selection.ends[-a]){this.clearSelection().show();return}this.selection.retractDir(a)}else{if(this[a])this.hopDir(a);else{if(this.parent===this.root)return;this.insDirOf(a,this.parent.parent)}this.hide().selection=ea(this[-a])}this.root.selectionChanged()};b.selectLeft=function(){return this.selectDir(-1)};b.selectRight=
function(){return this.selectDir(1)};b.prepareMove=function(){this.upDownCache={};return this.show().clearSelection()};b.prepareEdit=function(){this.upDownCache={};return this.show().deleteSelection()};b.prepareWrite=function(){this.upDownCache={};return this.show().replaceSelection()};b.clearSelection=function(){this.selection&&(this.selection.clear(),delete this.selection,this.root.selectionChanged());return this};b.deleteSelection=function(){if(!this.selection)return!1;this[-1]=this.selection.ends[-1][-1];
this[1]=this.selection.ends[1][1];this.selection.remove();this.root.selectionChanged();return delete this.selection};b.replaceSelection=function(){var a=this.selection;a&&(this[-1]=a.ends[-1][-1],this[1]=a.ends[1][1],delete this.selection);return a}}),ea=g(R,function(a,b){a.init=function(){b.init.apply(this,arguments);this.jQwrap(this.jQ)};a.jQwrap=function(a){this.jQ=a.wrapAll('<span class="selection"></span>').parent()};a.adopt=function(){this.jQ.replaceWith(this.jQ=this.jQ.children());return b.adopt.apply(this,
arguments)};a.clear=function(){this.jQ.replaceWith(this.jQ.children());return this};a.levelUp=function(){var a=this.ends[-1]=this.ends[1]=this.ends[1].parent.parent;this.clear().jQwrap(a.jQ);return this};a.extendDir=function(a){E(a);this.ends[a]=this.ends[a][a];this.ends[a].jQ.insAtDirEnd(a,this.jQ);return this};a.extendLeft=function(){return this.extendDir(-1)};a.extendRight=function(){return this.extendDir(1)};a.retractDir=function(a){E(a);this.ends[-a].jQ.insDirOf(-a,this.jQ);this.ends[-a]=this.ends[-a][a]};
a.retractRight=function(){return this.retractDir(1)};a.retractLeft=function(){return this.retractDir(-1)}});H.fn.mathquill=function(d,g,f){switch(d){case "setImg":alert("\ub118\uc5b4\uc628\uac12==>"+g);case "redraw":return this.each(function(){var a=r(this).attr("mathquill-block-id");(a=a&&p[a])&&function t(a){a.eachChild(t);a.redraw&&a.redraw()}(a)});case "revert":return this.each(function(){var a=r(this).attr("mathquill-block-id");(a=a&&p[a])&&a.revert&&a.revert()});case "latex":if(1<arguments.length)return this.each(function(){var a=
r(this).attr("mathquill-block-id");(a=a&&p[a])&&a.renderLatex(g)});var c=r(this).attr("mathquill-block-id");return(c=c&&p[c])&&c.latex();case "text":return(c=(c=r(this).attr("mathquill-block-id"))&&p[c])&&c.text();case "html":return this.html().replace(/ ?hasCursor|hasCursor /,"").replace(/ class=(""|(?= |>))/g,"").replace(/<span class="?cursor( blink)?"?><\/span>/i,"").replace(/<span class="?textarea"?><textarea><\/textarea><\/span>/i,"");case "write":if(1<arguments.length)return this.each(function(){var a=
r(this).attr("mathquill-block-id");(a=(a=a&&p[a])&&a.cursor)&&a.writeLatex(g).parent.blur()});case "ext":if(1<arguments.length)return a.img=b(v,"  "+f.get("extLatex"),'<img style="cursor:pointer" id="extImage_'+f.get("extId")+'" onclick="extUpdate('+f.get("extId")+',event);"  src="'+f.get("extImgSrc")+'"></img>'),this.each(function(){var a=r(this).attr("mathquill-block-id");(a=(a=a&&p[a])&&a.cursor)&&a.writeLatex(g).parent.blur()});case "manualDelete":return this.each(function(){var a=r(this).attr("mathquill-block-id");
(a=(a=a&&p[a])&&a.cursor)&&a.backspace()});case "allDelete":return alert("dont use by hong ss"),this.each(function(){var a=r(this).attr("mathquill-block-id"),a=a&&p[a];a.latex("");a&&function t(a){a.eachChild(t);try{a.remove()}catch(b){}}(a)});case "cmd":if(1<arguments.length)return this.each(function(){var a=r(this).attr("mathquill-block-id");if(a=(a=a&&p[a])&&a.cursor){var b=a.prepareWrite();/^\\[a-z]+$/i.test(g)?a.insertCmd(g.slice(1),b):a.insertCh(g,b);a.hide().parent.blur()}});default:var h=
"textbox"===d,k=h||"editable"===d,l=h?ha:N;return this.each(function(){aa(r(this),l(),h,k)})}};H(function(){H(".mathquill-editable:not(.mathquill-rendered-math)").mathquill("editable");H(".mathquill-textbox:not(.mathquill-rendered-math)").mathquill("textbox");H(".mathquill-embedded-latex").mathquill()})})();
