/*********************************************************************
*  <이든 수식편집>
*  위지윅 방식의 웹기반 수식편집기 입니다.
*  솔루션 구성은 클라이언트 모듈과 서버 모듈(java)로 구성되어 있습니다.
*  위지윅 방식으로 쉽게 수식입력이 가능하며 latex 문법으로도 수식입력이 가능합니다.
*  작성한 수식은 latex 및 mathml 또는 이미지로 변환이 가능하여 수식 답안 작성 및 게시판등에
*  이용이 가능합니다.    
*  무단 사용 및 배포를 금지합니다.  
*  솔루션 구입 연락처 : edenit@edenitsolution.com (02-2299-8250)
*  
*  EdenMath Editor
*  VERSION : 1.0.1
*  DOCS & DEMO : http://edenitsolution.com (http://edenit.co.kr)
*  CONTACT : edenit@edenitsolution.com
*  TEL : +82-02-2299-8250
*  
*  EdenMath Editor is web based wysiwyg math editor
*  support latex, mathml and image rendering
*  
*  Copyright (c) 2015-2016 by EDENIT Co.,Ltd  All Rights Reserved
*********************************************************************/

function addMath(b){var a="";switch(b){case "root":a="\\sqrt{}";break;case "nroot":a="\\sqrt[]{}";break;case "2nroot":a="\\sqrt[2]{}";break;case "3nroot":a="\\sqrt[3]{}";break;case "quadratic_formula1":a=" x={ \\frac{-b\\pm\\sqrt{b^2-4ac}}{2a} }";break;case "quadratic_formula2":a="\\sqrt{a^{2}+b^{2}}";break;case "frac":a="\\frac{}{}";break;case "high_frac1":a="\\frac{dy}{dx}";break;case "high_frac2":a="\\frac{\\Delta x}{\\Delta y}";break;case "high_frac3":a="\\frac{\\partial y}{\\partial x}";break;
case "high_frac4":a="\\frac{\\delta y}{\\delta x}";break;case "high_frac5":a="\\frac{\\pi}{2}";break;case "int":a="\\int_{}^{}";break;case "int2":a="\\int\\int_{2}^{1}";break;case "int1":a="\\int";break;case "iint":a="\\int\\int";break;case "iiint":a="\\int\\int\\int";break;case "line_int":a="\\oint";break;case "lim":a="\\lim_{}";break;case "dx":a="dx";break;case "dy":a="dy";break;case "dtheta":a="d\\theta";break;case "ln":a="\\ln{}";break;case "min":a="\\min_{}";break;case "max":a="\\max_{}";
break;case "lim_func":a="\\lim_{n \\rarr \\inf} {} \\left ( 1 + \\frac{1}{n} \\right )^{n}";break;case "max_func":a="\\max_{0 \\leq x \\leq 1} xe^{-x^{2}}";break;case "matrix22":a="\\vector{}";break;case "binom":a="\\binom{}{}";break;case "binom2":a="\\binom{n}{k}";break;case "sum":a="\\sum";break;case "sum2":a="\\sum_{}^{}";break;case "prod":a="\\prod";break;case "prod2":a="\\prod_{}^{}";break;case "coprod":a="\\coprod";break;case "coprod2":a="\\coprod_{}^{}";break;case "bigcup":a="\\bigcup";break;
case "bigcup2":a="\\bigcup_{}^{}";break;case "bigcap":a="\\bigcap";break;case "bigcap2":a="\\bigcap_{}^{}";break;case "vee":a="\\vee";break;case "vee2":a="\\vee_{}^{}";break;case "wedge":a="\\wedge";break;case "wedge2":a="\\wedge_{}^{}";break;case "normal_op1":a="\\sum_{k}\\left(\\frac{n}{k}\\right)";break;case "normal_op2":a="\\sum_{i=0}^{n}";break;case "normal_op3":a="\\prod_{k=1}^{n}A_{k}";break;case "normal_op4":a="\\sum_{0 \\le i \\le m , 0 \\lt j \\lt n}P(i,j)";break;case "normal_op5":a="\\bigcup_{n=1}^{m}\\left(X _{n} \\bigcap Y _{n} \\right)";
break;case "brackets1":a="\\left ( \\right )";break;case "brackets2":a="\\left \\{ \\right \\}";break;case "brackets3":a="\\left [ \\right ]";break;case "brackets4":a="\\langle{}";break;case "brackets5":a="\\left | \\right |";break;case "floor":a="\\lfloor \\rfloor";break;case "ceil":a="\\lceil \\rceil";break;case "div_brackets1":a="\\left ( {} \\vert {} \\right)";break;case "div_brackets2":a="\\left \\{ {} \\vert {} \\right \\}";break;case "div_brackets3":a="\\left \\langle {123} \\vert {123} \\right \\rangle";
break;case "div_brackets4":a="\\left \\langle {123} \\vert {123} \\vert {123} \\right \\rangle";break;case "bar1":a="\\bar { ) {123}}";break;case "bar2":a="\\underline{)123}";break;case "bar3":a="\\left \\langle {123} \\vert {123} \\vert {123} \\right \\rangle";break;case "bar4":a="\\left \\langle {123} \\vert {123} \\vert {123} \\right \\rangle";break;case "n^":a="n^{}";break;case "n_":a="n_{}";break;case "_^n":a="_{n}^{1}Y";break;case "n_^":a="Y_{1}^{2}";break;case "x_y^2":a="x_{y}^{2}";
break;case "x^2":a="x^{2}";break;case "e^{-iwt}":a="e^{-iwt}";break;case "1_^nY":a="_{1}^{n}Y";break;case "log":a="\\log";break;case "logx":a="\\log{}";break;case "log_x":a="\\log_{}";break;case "overline":a="\\overline{ABC}";break;case "accent":a="{a}'";break;case "double_accent":a="{a}''";break;case "dot":a="\\dot{}";break;case "ddot":a="\\ddot{a}";break;case "tdot":a="\\tdot{a}";break;case "hat":a="\\hat{a}";break;case "check":a="\\check{a}";break;case "grave":a="\\grave{a}";
break;case "acute":a="\\acute{a}";break;case "tilde":a="\\tilde{a}";break;case "breve":a="\\breve{a}";break;case "bar":a="\\bar{a}";break;case "vec":a="\\vec{a}";break;case "not":a="\\not{a}";break;case "circ":a="a^{\\circ}";break;case "overrightarrow":a="\\overrightarrow{}";break;case "overleftarrow":a="\\overleftarrow{}";break;case "underrightarrow":a="\\underrightarrow{}";break;case "underrightarrow2":a="\\underrightarrow{yields}";break;case "underrightarrow3":a="\\underrightarrow{\\Delta}";break;
case "underleftarrow":a="\\underleftarrow{}";break;case "overleftrightarrow":a="\\overleftrightarrow{}";break;case "underleftrightarrow":a="\\underleftrightarrow{}";break;case "triFunc1":a="sin\\alpha \\pm sin\\beta = 2sin\\frac{1}{2}\\left ( \\alpha \\pm \\beta \\right )cos\\frac{1}{2}\\left ( \\alpha \\mp \\beta \\right )";break;case "triFunc2":a="cos\\alpha \\pm cos\\beta = 2cos\\frac{1}{2}\\left ( \\alpha + \\beta \\right )cos\\frac{1}{2}\\left ( \\alpha - \\beta \\right )";break;case "circle_area":a=
"A = \\pi r^{2}";break;case "binomial_theorem":a="\\left (x + a \\right )^{n} = \\sum_{k = 0}^{n}\\binom{n}{k}x^{k}a^{n - k}";break;case "taylor":a="e^{x} = 1 + \\frac{x}{1!} + \\frac{x^{2}}{2!} + \\frac{x^{3}}{3!}+ \\ldots, - \\inf < x < \\inf";break;case "fourier":a="f\\left ( x \\right) = a_{0} + \\sum_{n = 1}^{\\inf}\\left (a_{n}cos\\frac{n \\pi x}{L} + b_{n} sin \\frac{n \\pi x}{L} \\right )";break;case "pythagoras":a="a^{2} + b^{2} = c^{2}";break;case "sum_expansion":a="\\left (1 + x \\right )^{n} = 1 + \\frac{nx}{1!} + \\frac{n \\left (n - 1 \\right )x^{2}}{2!} + \\ldots";
break;case "abc":alert("\ubcf4\ub958");break;case ":=":a=":=";break;case "==":a="==";break;case "+=":a="+=";break;case "-=":a="-=";break;default:a="aaaa"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addTriFunc(b,a){var c="";switch(b){case "sin":c=1==a?"\\sin":"\\sin^{-1}";break;case "cos":c=1==a?"\\cos":"\\cos^{-1}";break;case "tan":c=1==a?"\\tan":"\\tan^{-1}";break;case "csc":c=1==a?"\\csc":"\\csc^{-1}";break;case "sec":c=1==a?"\\sec":"\\sec^{-1}";break;case "cot":c=1==a?"\\cot":"\\cot^{-1}";break;case "sinh":c=1==a?"\\sinh":"\\sinh^{-1}";break;case "cosh":c=1==a?"\\cosh":"\\cosh^{-1}";break;case "tanh":c=1==a?"\\tanh":"\\tanh^{-1}";break;case "csch":c=1==a?"\\csch":"\\csch^{-1}";break;
case "sech":c=1==a?"\\sech":"\\sech^{-1}";break;case "coth":c=1==a?"\\coth":"\\coth^{-1}";break;case "sin_theta":c="\\sin\\theta";break;case "cos2x":c="\\cos2x";break;case "tan_theta":c="\\tan\\theta = \\frac{\\sin\\theta}{\\cos\\theta}";break;default:c="bbbb"}$(_targetEditor).mathquill("write",c);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsArrow(b){var a="";switch(b){case "longleftarrow":a="\\longleftarrow";break;case "longrightarrow":a="\\longrightarrow";break;case "Longleftarrow":a="\\Longleftarrow";break;case "Longrightarrow":a="\\Longrightarrow";break;case "longleftrightarrow":a="\\longleftrightarrow";break;case "updownarrow":a="\\updownarrow";break;case "Longleftrightarrow":a="\\Longleftrightarrow";break;case "Updownarrow":a="\\Updownarrow";break;case "mapsto":a="\\mapsto";break;case "nearrow":a="\\nearrow";
break;case "hookleftarrow":a="\\hookleftarrow";break;case "hookrightarrow":a="\\hookrightarrow";break;case "searrow":a="\\searrow";break;case "leftharpoonup":a="\\leftharpoonup";break;case "rightharpoonup":a="\\rightharpoonup";break;case "swarrow":a="\\swarrow";break;case "leftharpoondown":a="\\leftharpoondown";break;case "rightharpoondown":a="\\rightharpoondown";break;case "nwarrow":a="\\nwarrow";break;case "downarrow":a="\\downarrow";break;case "Downarrow":a="\\Downarrow";break;case "uparrow":a=
"\\uparrow";break;case "Uparrow":a="\\Uparrow";break;case "rightarrow":a="\\rightarrow";break;case "Rightarrow":a="\\Rightarrow";break;case "leftarrow":a="\\leftarrow";break;case "lArr":a="\\lArr";break;case "leftrightarrow":a="\\leftrightarrow";break;case "Leftrightarrow":a="\\Leftrightarrow";break;default:a="arrow"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsBasic(b){var a="";switch(b){case "infty":a="\\infty";break;case "emptyset":a="\\emptyset";break;case "deg":a="\\deg";break;case "nabla":a="\\nabla";break;case "ldots":a="\\ldots";break;case "cdots":a="\\cdots";break;case "vdots":a="\\vdots";break;case "ddots":a="\\ddots";break;case "prime":a="\\prime";break;case "percent":a="\\percent";break;case "factorial":a="!";break;default:a="basic"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();
".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsBinary(b){var a="";switch(b){case "+":a="\\+";break;case "-":a="\\-";break;case "times":a="\\times";break;case "div":a="\\div";break;case "pm":a="\\pm";break;case "mp":a="\\mp";break;case "propto":a="\\propto";break;case "slash":a="\\slash";break;case "ast":a="\\ast";break;case "circ":a="\\circ";break;case "cdot":a="\\cdot";break;case "cap":a="\\cap";break;case "cup":a="\\cup";break;case "uplus":a="\\uplus";break;case "sqcap":a="\\sqcap";break;case "sqcup":a="\\sqcup";break;case "wedge":a=
"\\wedge";break;case "vee":a="\\vee";break;default:a="binaryOperator"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsRelationships(b){var a="";switch(b){case "=":a="\\=";break;case "ne":a="\\ne";break;case "<":a="\\<";break;case ">":a="\\>";break;case "le":a="\\le";break;case "ge":a="\\ge";break;case "equiv":a="\\equiv";break;case "sim":a="\\sim";break;case "cong":a="\\cong";break;case "approx":a="\\approx";break;case "notin":a="\\notin";break;case "ll":a="\\ll";break;case "gg":a="\\gg";break;case "in":a="\\in";break;case "ni":a="\\ni";break;case "notni":a="\\notni";break;case "subset":a="\\subset";
break;case "supset":a="\\supset";break;case "subseteq":a="\\subseteq";break;case "supseteq":a="\\supseteq";break;case "prec":a="\\prec";break;case "succ":a="\\succ";break;case "preceq":a="\\preceq";break;case "succeq":a="\\succeq";break;case "sqsubset":a="\\sqsubset";break;case "sqsupset":a="\\sqsupset";break;case "sqsubseteq":a="\\sqsubseteq";break;case "sqsupseteq":a="\\sqsupseteq";break;case "parallel":a="\\parallel";break;case "perp":a="\\perp";break;case "vdash":a="\\vdash";break;case "dashv":a=
"\\dashv";break;case "bowtie":a="\\bowtie";break;case "asymp":a="\\asymp";break;case "overequal":a="\\overequal";break;case "approximatelyequal":a="\\approximatelyequal";break;default:a="relations"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsNegatedRelationships(b){var a="";switch(b){case "nless":a="\\nless";break;case "nleqslant":a="\\nleqslant";break;case "ngtr":a="\\ngtr";break;case "ngeqslant":a="\\ngeqslant";break;case "lnsim":a="\\lnsim";break;case "gnsim":a="\\gnsim";break;case "nparallel":a="\\nparallel";break;case "nvDash":a="\\nvDash";break;case "nVDash":a="\\nVDash";break;case "nMember":a="\\nMember";break;case "nsub":a="\\nsub";break;case "nsup":a="\\nsup";break;default:a="relations"}$(_targetEditor).mathquill("write",
a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsHighBinary(b){var a="";switch(b){case "setminus":a="\\setminus";break;case "oplus":a="\\oplus";break;case "ominus":a="\\ominus";break;case "otimes":a="\\otimes";break;case "oslash":a="\\oslash";break;case "odot":a="\\odot";break;case "dagger":a="\\dagger";break;case "ddagger":a="\\ddagger";break;case "uplus":a="\\uplus";break;case "wr":a="\\wr";break;default:a="HighBinary"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==
_targetEditor&&syncEditorAndSource()}function addSymbolsHighRelationships(b){var a="";switch(b){case "therefore":a="\\therefore";break;case "because":a="\\because";break;case "doteq":a="\\doteq";break;case "models":a="\\models";break;default:a="HighRelationships"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsText(b){var a="";switch(b){case "forall":a="\\forall";break;case "partial":a="\\partial";break;case "hbar":a="\\hbar";break;case "AA":a="\\AA";break;case "mho":a="\\mho";break;case "wp":a="\\wp";break;case "Re":a="\\Re";break;case "Im":a="\\Im";break;case "exists":a="\\exists";break;case "aleph":a="\\aleph";break;default:a="SymbolsText"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&
syncEditorAndSource()}function addSymbolsGeometricalFigure(b){var a="";switch(b){case "angle":a="\\angle";break;case "bot":a="\\bot";break;default:a="SymbolsText"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addSymbolsGreek(b){var a="";switch(b){case "alpha":a="\\alpha";break;case "beta":a="\\beta";break;case "gamma":a="\\gamma";break;case "delta":a="\\delta";break;case "epsilon":a="\\epsilon";break;case "zeta":a="\\zeta";break;case "eta":a="\\eta";break;case "theta":a="\\theta";break;case "iota":a="\\iota";break;case "kappa":a="\\kappa";break;case "lambda":a="\\lambda";break;case "mu":a="\\mu";break;case "nu":a="\\nu";break;case "xi":a="\\xi";break;case "pi":a="\\pi";break;case "rho":a="\\rho";
break;case "sigma":a="\\sigma";break;case "tau":a="\\tau";break;case "upsilon":a="\\upsilon";break;case "phi":a="\\phi";break;case "chi":a="\\chi";break;case "psi":a="\\psi";break;case "omega":a="\\omega";break;case "digamma":a="\\digamma";break;case "varepsilon":a="\\varepsilon";break;case "vartheta":a="\\vartheta";break;case "varkappa":a="\\varkappa";break;case "varpi":a="\\varpi";break;case "varrho":a="\\varrho";break;case "varsigma":a="\\varsigma";break;case "varphi":a="\\varphi";break;case "Gamma":a=
"\\Gamma";break;case "Delta":a="\\Delta";break;case "Theta":a="\\Theta";break;case "Lambda":a="\\Lambda";break;case "Xi":a="\\Xi";break;case "Pi":a="\\Pi";break;case "Sigma":a="\\Sigma";break;case "Upsilon":a="\\Upsilon";break;case "Phi":a="\\Phi";break;case "Psi":a="\\Psi";break;case "Omega":a="\\Omega";break;default:a="greek"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()}
function addEdenCustomEQ(b){var a="";switch(b){case "edenCmdStackTwo":a="\\edenCmdStackTwo{}{}";break;case "edenCmdStackThree":a="\\edenCmdStackThree{}{}{}";break;case "edenCmdBinom":a="\\edenCmdBinom{}{}";break;case "edenCmdSumStack":a="\\sum_{k}\\edenCmdBinom{n}{k}";break;default:a="greek"}$(_targetEditor).mathquill("write",a);$(".tabmenu a").removeClass("on");$(".tab-conwrap .tabcon").hide();".mathquill-editable.default"==_targetEditor&&syncEditorAndSource()};
